core:
  plans:
    app:
      type: dev
    view: {path: $SELF/mvc}

gpt:
  default:
    n_embd: 16  # embedding dimension
    n_head: 4   # number of attention heads
    n_layer: 1  # number of layers
    block_size: 16 # (8) maximum sequence length, note: the longest name is 15 characters
    grad_clip: 1.0
    n_train: 100
    n_inference: 10
    learning_rate: 1e-2 # learning_rate, beta1, beta2, eps_adam = 1e-2, 0.9, 0.95, 1e-8
    temperature: 0.6    # learning_rate, beta1, beta2, eps_adam = 0.01, 0.85, 0.99, 1e-8
  short:
    e: n_embd
    l: n_layer
    h: n_head
    x: n_train
    y: n_inference
    b: block_size
    c: grad_clip
    r: learning_rate
    t: temperature
  str: [Default configuration:, Running with:]
  v:
    settings: []
    is_train: true
    txt: false
    bin: false 
    qtz: false 
    rnd: 42
  usage: $TAIL1

data:
  default:
    filename: default_dataset
    n_samples: 2000
    max_val: 9
    block_size: 8
    type: ???
  short:
    fn: filename
    n: n_samples
    m: max_val
    bs: block_size
    t: type
  v: []
  usage: $TAIL2
~

USAGE:
Run the Logos ware (train &| inference) as:
>sky logos z param1=value1 param2=value2 ...

PARAMATERS:
  txt: take dataset file from `txt` dir
  bin: load or save bin-file model;
  qtz: bin-file will written if quantization present; options: 4|8|32
  rnd: exec mt_srand(num); mt_srand(42) by default; set rnd=0 to turn off
  + see single-character parameters below
SAMPLES:
  >sky logos z txt=math x=500 y=11
  (take dataset from `txt/math.txt` path)

  >sky logos z bin=math y=11
  (inference only: run file-model from `bin/math.bin` path)

  >sky logos z txt=math bin=math x=10000 qtz=4
  (train 10000 steps, then save `bin/math.bin` model-file)

  TODO: continue training bin-model

Single-character parameters:
%list_1%

Default configuration:
%list_2%

~
USAGE:
  Run the Logos ware (dataset generation) as:
  >sky logos g param1=value1 param2=value2 ...
SHORT PARAMATERS:
  %list_1%
TYPES ARE: (one of is must)
  math - Simple addition
  dna - Synthetic DNA
SAMPLES:
  >sky logos g t=math n=500 fn=math_test
  (generate math 500 samples dataset to file `txt/math_test.txt`)
CURRENT CONFIGURATION:
%list_2%

~

